package cmd

import (
	"fmt"
	"os"
	"strings"
	"sync"

	"github.com/spf13/cobra"
	"github.com/opscores/umesh-cli/internal/nodeinit"
	"github.com/opscores/umesh-cli/internal/role"
	"github.com/opscores/umesh-cli/internal/uio"
)

// Flags provides access to the global persistent flags shared by commands.
type Flags struct {
	Container string
	RPCURL    string
	Home      string
	Image     string
	DataDir   string
	Verbose   bool
	Quiet     bool
	NoColor   bool
}

var global Flags
var globalMu sync.Mutex

// GlobalFlags returns a thread-safe copy of global flags.
func GlobalFlags() Flags {
	globalMu.Lock()
	defer globalMu.Unlock()
	return global
}

// SetGlobalFlags updates global flags with a mutex.
func SetGlobalFlags(f Flags) {
	globalMu.Lock()
	defer globalMu.Unlock()
	global = f
}

// NewRootCmd builds the root command tree for umeshctl.
// umeshctl is a host-side CLI for initializing and administering Umesh nodes.
//
// Commands are organized by lifecycle phase:
//   - init:  node initialization (validator, sentry, rpc, genesis)
//   - setup: pre-launch operations (plan, tune, keys add)
//   - node:  runtime operations (status, validator, sentry, keys)
//   - ops:   maintenance operations (backup, doctor, verify)
//   - genesis: genesis utilities for coordinators
func NewRootCmd() *cobra.Command {
	root := &cobra.Command{
		Use:     "umeshctl",
		Short:   "Umesh node administration CLI (host-side)",
		Version: Version,
		Long: `umeshctl — host-side CLI for initializing and administering Umesh nodes.

Commands are organized by lifecycle phase:

  init     — node initialization (validator, sentry, rpc, genesis)
  setup    — pre-launch operations (plan, tune, keys add)
  node     — after launch (status, validator, sentry, keys)
  ops      — maintenance (backup, doctor, verify)
  genesis  — genesis utilities (fetch, inspect, validate, collect)

Environment variables (also accepted as flags):
  UMESH_HOME         — host data directory (auto: ./data-validator|./data-sentry|./data-rpc)
  SENTRY_RPC         — sentry RPC endpoint for cross-role checks
  SENTRY_RPC_FALLBACK— fallback sentry RPC endpoint
  NODE_IMAGE         — container image (default: umesh-node:latest)

Examples:
  umeshctl init validator --config config.yaml
  umeshctl init sentry --config config.yaml --sentry-rpc http://10.0.0.5:26657
  umeshctl genesis plan --config plan.yaml       # production genesis
  umeshctl node status sync                   # check sync status
  umeshctl ops backup --output ./backups       # backup keys`,
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
			uio.SetVerbose(global.Verbose)
			uio.SetQuiet(global.Quiet)
			uio.SetColorMode(global.NoColor || os.Getenv("NO_COLOR") != "")
			if global.DataDir == "" {
				global.DataDir = nodeinit.DetectHome()
			}
			uio.LogDebug("data-dir: %s, home: %s, image: %s", global.DataDir, global.Home, global.Image)

			if allowed, ok := roleGuardFor(cmd); ok {
				_, err := role.Check(cmd, allowed)
				return err
			}
			return nil
		},
		SilenceUsage:  true,
		SilenceErrors: true,
	}

	pf := root.PersistentFlags()
	pf.StringVar(&global.Container, "container", "umesh-validator", "Docker container name")
	pf.StringVar(&global.RPCURL, "rpc-url", "http://127.0.0.1:26657", "RPC endpoint URL")
	pf.StringVar(&global.Home, "home", "/home/umesh/.umeshnode", "Node home path inside container")
	pf.StringVar(&global.Image, "image", "umesh-node:latest", "Container image used for offline operations")
	pf.StringVar(&global.DataDir, "data-dir", "", "Host data directory (auto: ./data-validator | ./data-sentry | ./data-rpc, by role)")
	pf.BoolVar(&global.Verbose, "verbose", false, "Verbose output")
	pf.BoolVar(&global.Quiet, "quiet", false, "Suppress non-essential output (errors only)")
	pf.BoolVar(&global.NoColor, "no-color", false, "Disable colored output (also respects NO_COLOR env)")

	root.SetOut(os.Stdout)
	root.SetErr(os.Stderr)

	root.AddCommand(
		newInitCmd(),
		newValidatorCmd(),
		newSentryCmd(),
		newSetupCmd(),
		newNodeCmd(),
		newOpsCmd(),
		newGenesisCmd(),
		newRPCCmd(),
		newVersionCmd(),
		newCompletionCmd(root),
	)

	return root
}

func roleGuardFor(cmd *cobra.Command) ([]string, bool) {
	for c := cmd; c != nil; c = c.Parent() {
		if g := c.Annotations["role-guard"]; g != "" {
			return strings.Split(g, ","), true
		}
	}
	return nil, false
}

// newCompletionCmd exposes shell completion generated by cobra.
func newCompletionCmd(root *cobra.Command) *cobra.Command {
	return &cobra.Command{
		Use:   "completion [bash|zsh|fish|powershell]",
		Short: "Generate the autocompletion script for the specified shell",
		Args:  cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
		RunE: func(cmd *cobra.Command, args []string) error {
			switch args[0] {
			case "bash":
				return root.GenBashCompletion(cmd.OutOrStdout())
			case "zsh":
				return root.GenZshCompletion(cmd.OutOrStdout())
			case "fish":
				return root.GenFishCompletion(cmd.OutOrStdout(), true)
			case "powershell":
				return root.GenPowerShellCompletion(cmd.OutOrStdout())
			}
			return fmt.Errorf("unknown shell: %s", args[0])
		},
	}
}
